services:
    php:
        image: ${IMAGES_PREFIX:-}app-php
        restart: unless-stopped
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
            MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
            DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
            # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
            MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
            MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
            MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            # The two next lines can be removed after initial installation
            SYMFONY_VERSION: ${SYMFONY_VERSION:-}
            STABILITY: ${STABILITY:-stable}
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        ports:
            # HTTP
            - target: 80
              published: ${HTTP_PORT:-80}
              protocol: tcp
            # HTTPS
            - target: 443
              published: ${HTTPS_PORT:-443}
              protocol: tcp
            # HTTP/3
            - target: 443
              published: ${HTTP3_PORT:-443}
              protocol: udp
    
    rabbitmq-node-1:
        image: rabbitmq:3.12-management
        hostname: rabbitmq-node-1
        container_name: rabbitmq-node-1
        restart: unless-stopped
        environment:
            RABBITMQ_ERLANG_COOKIE: "RABBITMQ_ERLANG_COOKIE"
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data_1:/var/lib/rabbitmq
        networks:
            - rabbitmq_net
    
    rabbitmq-node-2:
        image: rabbitmq:3.12-management
        hostname: rabbitmq-node-2
        container_name: rabbitmq-node-2
        restart: unless-stopped
        environment:
            RABBITMQ_ERLANG_COOKIE: "RABBITMQ_ERLANG_COOKIE"
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        volumes:
            - rabbitmq_data_2:/var/lib/rabbitmq
        networks:
            - rabbitmq_net
        depends_on:
            - rabbitmq-node-1

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

networks:
    rabbitmq_net:
        driver: bridge

volumes:
    caddy_data:
    caddy_config:
    rabbitmq_data_1:
    rabbitmq_data_2:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
